/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PeminjamRouteRouteImport } from './routes/peminjam/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PeminjamIndexRouteImport } from './routes/peminjam/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminPeminjamanRuangRouteImport } from './routes/admin/peminjaman-ruang'
import { Route as AdminUsersIndexRouteImport } from './routes/admin/users/index'
import { Route as AdminManajemenRuangIndexRouteImport } from './routes/admin/manajemen-ruang/index'
import { Route as AdminUsersEditRouteImport } from './routes/admin/users/edit'
import { Route as AdminUsersAddRouteImport } from './routes/admin/users/add'
import { Route as AdminManajemenRuangEditRouteImport } from './routes/admin/manajemen-ruang/edit'
import { Route as AdminManajemenRuangAddRouteImport } from './routes/admin/manajemen-ruang/add'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PeminjamRouteRoute = PeminjamRouteRouteImport.update({
  id: '/peminjam',
  path: '/peminjam',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PeminjamIndexRoute = PeminjamIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PeminjamRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPeminjamanRuangRoute = AdminPeminjamanRuangRouteImport.update({
  id: '/peminjaman-ruang',
  path: '/peminjaman-ruang',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminManajemenRuangIndexRoute =
  AdminManajemenRuangIndexRouteImport.update({
    id: '/manajemen-ruang/',
    path: '/manajemen-ruang/',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminUsersEditRoute = AdminUsersEditRouteImport.update({
  id: '/users/edit',
  path: '/users/edit',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUsersAddRoute = AdminUsersAddRouteImport.update({
  id: '/users/add',
  path: '/users/add',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminManajemenRuangEditRoute = AdminManajemenRuangEditRouteImport.update({
  id: '/manajemen-ruang/edit',
  path: '/manajemen-ruang/edit',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminManajemenRuangAddRoute = AdminManajemenRuangAddRouteImport.update({
  id: '/manajemen-ruang/add',
  path: '/manajemen-ruang/add',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/peminjam': typeof PeminjamRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/peminjaman-ruang': typeof AdminPeminjamanRuangRoute
  '/admin/': typeof AdminIndexRoute
  '/peminjam/': typeof PeminjamIndexRoute
  '/admin/manajemen-ruang/add': typeof AdminManajemenRuangAddRoute
  '/admin/manajemen-ruang/edit': typeof AdminManajemenRuangEditRoute
  '/admin/users/add': typeof AdminUsersAddRoute
  '/admin/users/edit': typeof AdminUsersEditRoute
  '/admin/manajemen-ruang': typeof AdminManajemenRuangIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/peminjaman-ruang': typeof AdminPeminjamanRuangRoute
  '/admin': typeof AdminIndexRoute
  '/peminjam': typeof PeminjamIndexRoute
  '/admin/manajemen-ruang/add': typeof AdminManajemenRuangAddRoute
  '/admin/manajemen-ruang/edit': typeof AdminManajemenRuangEditRoute
  '/admin/users/add': typeof AdminUsersAddRoute
  '/admin/users/edit': typeof AdminUsersEditRoute
  '/admin/manajemen-ruang': typeof AdminManajemenRuangIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/peminjam': typeof PeminjamRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/peminjaman-ruang': typeof AdminPeminjamanRuangRoute
  '/admin/': typeof AdminIndexRoute
  '/peminjam/': typeof PeminjamIndexRoute
  '/admin/manajemen-ruang/add': typeof AdminManajemenRuangAddRoute
  '/admin/manajemen-ruang/edit': typeof AdminManajemenRuangEditRoute
  '/admin/users/add': typeof AdminUsersAddRoute
  '/admin/users/edit': typeof AdminUsersEditRoute
  '/admin/manajemen-ruang/': typeof AdminManajemenRuangIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/peminjam'
    | '/login'
    | '/admin/peminjaman-ruang'
    | '/admin/'
    | '/peminjam/'
    | '/admin/manajemen-ruang/add'
    | '/admin/manajemen-ruang/edit'
    | '/admin/users/add'
    | '/admin/users/edit'
    | '/admin/manajemen-ruang'
    | '/admin/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin/peminjaman-ruang'
    | '/admin'
    | '/peminjam'
    | '/admin/manajemen-ruang/add'
    | '/admin/manajemen-ruang/edit'
    | '/admin/users/add'
    | '/admin/users/edit'
    | '/admin/manajemen-ruang'
    | '/admin/users'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/peminjam'
    | '/login'
    | '/admin/peminjaman-ruang'
    | '/admin/'
    | '/peminjam/'
    | '/admin/manajemen-ruang/add'
    | '/admin/manajemen-ruang/edit'
    | '/admin/users/add'
    | '/admin/users/edit'
    | '/admin/manajemen-ruang/'
    | '/admin/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  PeminjamRouteRoute: typeof PeminjamRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/peminjam': {
      id: '/peminjam'
      path: '/peminjam'
      fullPath: '/peminjam'
      preLoaderRoute: typeof PeminjamRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/peminjam/': {
      id: '/peminjam/'
      path: '/'
      fullPath: '/peminjam/'
      preLoaderRoute: typeof PeminjamIndexRouteImport
      parentRoute: typeof PeminjamRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/peminjaman-ruang': {
      id: '/admin/peminjaman-ruang'
      path: '/peminjaman-ruang'
      fullPath: '/admin/peminjaman-ruang'
      preLoaderRoute: typeof AdminPeminjamanRuangRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/manajemen-ruang/': {
      id: '/admin/manajemen-ruang/'
      path: '/manajemen-ruang'
      fullPath: '/admin/manajemen-ruang'
      preLoaderRoute: typeof AdminManajemenRuangIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/users/edit': {
      id: '/admin/users/edit'
      path: '/users/edit'
      fullPath: '/admin/users/edit'
      preLoaderRoute: typeof AdminUsersEditRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/users/add': {
      id: '/admin/users/add'
      path: '/users/add'
      fullPath: '/admin/users/add'
      preLoaderRoute: typeof AdminUsersAddRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/manajemen-ruang/edit': {
      id: '/admin/manajemen-ruang/edit'
      path: '/manajemen-ruang/edit'
      fullPath: '/admin/manajemen-ruang/edit'
      preLoaderRoute: typeof AdminManajemenRuangEditRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/manajemen-ruang/add': {
      id: '/admin/manajemen-ruang/add'
      path: '/manajemen-ruang/add'
      fullPath: '/admin/manajemen-ruang/add'
      preLoaderRoute: typeof AdminManajemenRuangAddRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminPeminjamanRuangRoute: typeof AdminPeminjamanRuangRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminManajemenRuangAddRoute: typeof AdminManajemenRuangAddRoute
  AdminManajemenRuangEditRoute: typeof AdminManajemenRuangEditRoute
  AdminUsersAddRoute: typeof AdminUsersAddRoute
  AdminUsersEditRoute: typeof AdminUsersEditRoute
  AdminManajemenRuangIndexRoute: typeof AdminManajemenRuangIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminPeminjamanRuangRoute: AdminPeminjamanRuangRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminManajemenRuangAddRoute: AdminManajemenRuangAddRoute,
  AdminManajemenRuangEditRoute: AdminManajemenRuangEditRoute,
  AdminUsersAddRoute: AdminUsersAddRoute,
  AdminUsersEditRoute: AdminUsersEditRoute,
  AdminManajemenRuangIndexRoute: AdminManajemenRuangIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface PeminjamRouteRouteChildren {
  PeminjamIndexRoute: typeof PeminjamIndexRoute
}

const PeminjamRouteRouteChildren: PeminjamRouteRouteChildren = {
  PeminjamIndexRoute: PeminjamIndexRoute,
}

const PeminjamRouteRouteWithChildren = PeminjamRouteRoute._addFileChildren(
  PeminjamRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  PeminjamRouteRoute: PeminjamRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
