/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TandaTanganRouteImport } from './routes/tanda-tangan'
import { Route as PreviewDokumenRouteImport } from './routes/preview-dokumen'
import { Route as LoginOptionRouteImport } from './routes/login-option'
import { Route as LoginRouteImport } from './routes/login'
import { Route as Wadek1RouteRouteImport } from './routes/wadek1/route'
import { Route as SumberDayaRouteRouteImport } from './routes/sumber-daya/route'
import { Route as SenatRouteRouteImport } from './routes/senat/route'
import { Route as PeminjamRouteRouteImport } from './routes/peminjam/route'
import { Route as KetuaOrmawaRouteRouteImport } from './routes/ketua-ormawa/route'
import { Route as KetuaDepartemenRouteRouteImport } from './routes/ketua-departemen/route'
import { Route as KemahasiswaanRouteRouteImport } from './routes/kemahasiswaan/route'
import { Route as DosenPendampingRouteRouteImport } from './routes/dosen-pendamping/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Wadek1IndexRouteImport } from './routes/wadek1/index'
import { Route as SumberDayaIndexRouteImport } from './routes/sumber-daya/index'
import { Route as SenatIndexRouteImport } from './routes/senat/index'
import { Route as PeminjamIndexRouteImport } from './routes/peminjam/index'
import { Route as KetuaOrmawaIndexRouteImport } from './routes/ketua-ormawa/index'
import { Route as KetuaDepartemenIndexRouteImport } from './routes/ketua-departemen/index'
import { Route as KemahasiswaanIndexRouteImport } from './routes/kemahasiswaan/index'
import { Route as DosenPendampingIndexRouteImport } from './routes/dosen-pendamping/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as Wadek1RiwayatPersetujuanRouteImport } from './routes/wadek1/riwayat-persetujuan'
import { Route as SumberDayaTambahPeminjamanRouteImport } from './routes/sumber-daya/tambah-peminjaman'
import { Route as SumberDayaRiwayatPersetujuanRouteImport } from './routes/sumber-daya/riwayat-persetujuan'
import { Route as SumberDayaManajemenRuangRouteImport } from './routes/sumber-daya/manajemen-ruang'
import { Route as SenatRiwayatPersetujuanRouteImport } from './routes/senat/riwayat-persetujuan'
import { Route as PeminjamReservasiRouteImport } from './routes/peminjam/reservasi'
import { Route as KetuaOrmawaSignRouteImport } from './routes/ketua-ormawa/sign'
import { Route as KetuaOrmawaRiwayatPersetujuanRouteImport } from './routes/ketua-ormawa/riwayat-persetujuan'
import { Route as KetuaOrmawaPreviewRouteImport } from './routes/ketua-ormawa/preview'
import { Route as KetuaDepartemenRiwayatPersetujuanRouteImport } from './routes/ketua-departemen/riwayat-persetujuan'
import { Route as KemahasiswaanRiwayatPersetujuanRouteImport } from './routes/kemahasiswaan/riwayat-persetujuan'
import { Route as DosenPendampingRiwayatPersetujuanRouteImport } from './routes/dosen-pendamping/riwayat-persetujuan'
import { Route as PeminjamPinjamIndexRouteImport } from './routes/peminjam/pinjam/index'
import { Route as AdminUsersIndexRouteImport } from './routes/admin/users/index'
import { Route as AdminPeminjamanRuangIndexRouteImport } from './routes/admin/peminjaman-ruang/index'
import { Route as AdminManajemenRuangIndexRouteImport } from './routes/admin/manajemen-ruang/index'
import { Route as PeminjamPinjamTandaTanganRouteImport } from './routes/peminjam/pinjam/tanda-tangan'
import { Route as PeminjamPinjamProposalRouteImport } from './routes/peminjam/pinjam/proposal'
import { Route as PeminjamPinjamEditDokumenRouteImport } from './routes/peminjam/pinjam/edit-dokumen'
import { Route as PeminjamPinjamDetailTempatRouteImport } from './routes/peminjam/pinjam/detail-tempat'
import { Route as AdminUsersEditRouteImport } from './routes/admin/users/edit'
import { Route as AdminUsersDetailRouteImport } from './routes/admin/users/detail'
import { Route as AdminUsersAddRouteImport } from './routes/admin/users/add'
import { Route as AdminManajemenRuangEditRouteImport } from './routes/admin/manajemen-ruang/edit'
import { Route as AdminManajemenRuangAddRouteImport } from './routes/admin/manajemen-ruang/add'

const TandaTanganRoute = TandaTanganRouteImport.update({
  id: '/tanda-tangan',
  path: '/tanda-tangan',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewDokumenRoute = PreviewDokumenRouteImport.update({
  id: '/preview-dokumen',
  path: '/preview-dokumen',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginOptionRoute = LoginOptionRouteImport.update({
  id: '/login-option',
  path: '/login-option',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const Wadek1RouteRoute = Wadek1RouteRouteImport.update({
  id: '/wadek1',
  path: '/wadek1',
  getParentRoute: () => rootRouteImport,
} as any)
const SumberDayaRouteRoute = SumberDayaRouteRouteImport.update({
  id: '/sumber-daya',
  path: '/sumber-daya',
  getParentRoute: () => rootRouteImport,
} as any)
const SenatRouteRoute = SenatRouteRouteImport.update({
  id: '/senat',
  path: '/senat',
  getParentRoute: () => rootRouteImport,
} as any)
const PeminjamRouteRoute = PeminjamRouteRouteImport.update({
  id: '/peminjam',
  path: '/peminjam',
  getParentRoute: () => rootRouteImport,
} as any)
const KetuaOrmawaRouteRoute = KetuaOrmawaRouteRouteImport.update({
  id: '/ketua-ormawa',
  path: '/ketua-ormawa',
  getParentRoute: () => rootRouteImport,
} as any)
const KetuaDepartemenRouteRoute = KetuaDepartemenRouteRouteImport.update({
  id: '/ketua-departemen',
  path: '/ketua-departemen',
  getParentRoute: () => rootRouteImport,
} as any)
const KemahasiswaanRouteRoute = KemahasiswaanRouteRouteImport.update({
  id: '/kemahasiswaan',
  path: '/kemahasiswaan',
  getParentRoute: () => rootRouteImport,
} as any)
const DosenPendampingRouteRoute = DosenPendampingRouteRouteImport.update({
  id: '/dosen-pendamping',
  path: '/dosen-pendamping',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Wadek1IndexRoute = Wadek1IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => Wadek1RouteRoute,
} as any)
const SumberDayaIndexRoute = SumberDayaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SumberDayaRouteRoute,
} as any)
const SenatIndexRoute = SenatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SenatRouteRoute,
} as any)
const PeminjamIndexRoute = PeminjamIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PeminjamRouteRoute,
} as any)
const KetuaOrmawaIndexRoute = KetuaOrmawaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => KetuaOrmawaRouteRoute,
} as any)
const KetuaDepartemenIndexRoute = KetuaDepartemenIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => KetuaDepartemenRouteRoute,
} as any)
const KemahasiswaanIndexRoute = KemahasiswaanIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => KemahasiswaanRouteRoute,
} as any)
const DosenPendampingIndexRoute = DosenPendampingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DosenPendampingRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const Wadek1RiwayatPersetujuanRoute =
  Wadek1RiwayatPersetujuanRouteImport.update({
    id: '/riwayat-persetujuan',
    path: '/riwayat-persetujuan',
    getParentRoute: () => Wadek1RouteRoute,
  } as any)
const SumberDayaTambahPeminjamanRoute =
  SumberDayaTambahPeminjamanRouteImport.update({
    id: '/tambah-peminjaman',
    path: '/tambah-peminjaman',
    getParentRoute: () => SumberDayaRouteRoute,
  } as any)
const SumberDayaRiwayatPersetujuanRoute =
  SumberDayaRiwayatPersetujuanRouteImport.update({
    id: '/riwayat-persetujuan',
    path: '/riwayat-persetujuan',
    getParentRoute: () => SumberDayaRouteRoute,
  } as any)
const SumberDayaManajemenRuangRoute =
  SumberDayaManajemenRuangRouteImport.update({
    id: '/manajemen-ruang',
    path: '/manajemen-ruang',
    getParentRoute: () => SumberDayaRouteRoute,
  } as any)
const SenatRiwayatPersetujuanRoute = SenatRiwayatPersetujuanRouteImport.update({
  id: '/riwayat-persetujuan',
  path: '/riwayat-persetujuan',
  getParentRoute: () => SenatRouteRoute,
} as any)
const PeminjamReservasiRoute = PeminjamReservasiRouteImport.update({
  id: '/reservasi',
  path: '/reservasi',
  getParentRoute: () => PeminjamRouteRoute,
} as any)
const KetuaOrmawaSignRoute = KetuaOrmawaSignRouteImport.update({
  id: '/sign',
  path: '/sign',
  getParentRoute: () => KetuaOrmawaRouteRoute,
} as any)
const KetuaOrmawaRiwayatPersetujuanRoute =
  KetuaOrmawaRiwayatPersetujuanRouteImport.update({
    id: '/riwayat-persetujuan',
    path: '/riwayat-persetujuan',
    getParentRoute: () => KetuaOrmawaRouteRoute,
  } as any)
const KetuaOrmawaPreviewRoute = KetuaOrmawaPreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => KetuaOrmawaRouteRoute,
} as any)
const KetuaDepartemenRiwayatPersetujuanRoute =
  KetuaDepartemenRiwayatPersetujuanRouteImport.update({
    id: '/riwayat-persetujuan',
    path: '/riwayat-persetujuan',
    getParentRoute: () => KetuaDepartemenRouteRoute,
  } as any)
const KemahasiswaanRiwayatPersetujuanRoute =
  KemahasiswaanRiwayatPersetujuanRouteImport.update({
    id: '/riwayat-persetujuan',
    path: '/riwayat-persetujuan',
    getParentRoute: () => KemahasiswaanRouteRoute,
  } as any)
const DosenPendampingRiwayatPersetujuanRoute =
  DosenPendampingRiwayatPersetujuanRouteImport.update({
    id: '/riwayat-persetujuan',
    path: '/riwayat-persetujuan',
    getParentRoute: () => DosenPendampingRouteRoute,
  } as any)
const PeminjamPinjamIndexRoute = PeminjamPinjamIndexRouteImport.update({
  id: '/pinjam/',
  path: '/pinjam/',
  getParentRoute: () => PeminjamRouteRoute,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPeminjamanRuangIndexRoute =
  AdminPeminjamanRuangIndexRouteImport.update({
    id: '/peminjaman-ruang/',
    path: '/peminjaman-ruang/',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminManajemenRuangIndexRoute =
  AdminManajemenRuangIndexRouteImport.update({
    id: '/manajemen-ruang/',
    path: '/manajemen-ruang/',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const PeminjamPinjamTandaTanganRoute =
  PeminjamPinjamTandaTanganRouteImport.update({
    id: '/pinjam/tanda-tangan',
    path: '/pinjam/tanda-tangan',
    getParentRoute: () => PeminjamRouteRoute,
  } as any)
const PeminjamPinjamProposalRoute = PeminjamPinjamProposalRouteImport.update({
  id: '/pinjam/proposal',
  path: '/pinjam/proposal',
  getParentRoute: () => PeminjamRouteRoute,
} as any)
const PeminjamPinjamEditDokumenRoute =
  PeminjamPinjamEditDokumenRouteImport.update({
    id: '/pinjam/edit-dokumen',
    path: '/pinjam/edit-dokumen',
    getParentRoute: () => PeminjamRouteRoute,
  } as any)
const PeminjamPinjamDetailTempatRoute =
  PeminjamPinjamDetailTempatRouteImport.update({
    id: '/pinjam/detail-tempat',
    path: '/pinjam/detail-tempat',
    getParentRoute: () => PeminjamRouteRoute,
  } as any)
const AdminUsersEditRoute = AdminUsersEditRouteImport.update({
  id: '/users/edit',
  path: '/users/edit',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUsersDetailRoute = AdminUsersDetailRouteImport.update({
  id: '/users/detail',
  path: '/users/detail',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUsersAddRoute = AdminUsersAddRouteImport.update({
  id: '/users/add',
  path: '/users/add',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminManajemenRuangEditRoute = AdminManajemenRuangEditRouteImport.update({
  id: '/manajemen-ruang/edit',
  path: '/manajemen-ruang/edit',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminManajemenRuangAddRoute = AdminManajemenRuangAddRouteImport.update({
  id: '/manajemen-ruang/add',
  path: '/manajemen-ruang/add',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/dosen-pendamping': typeof DosenPendampingRouteRouteWithChildren
  '/kemahasiswaan': typeof KemahasiswaanRouteRouteWithChildren
  '/ketua-departemen': typeof KetuaDepartemenRouteRouteWithChildren
  '/ketua-ormawa': typeof KetuaOrmawaRouteRouteWithChildren
  '/peminjam': typeof PeminjamRouteRouteWithChildren
  '/senat': typeof SenatRouteRouteWithChildren
  '/sumber-daya': typeof SumberDayaRouteRouteWithChildren
  '/wadek1': typeof Wadek1RouteRouteWithChildren
  '/login': typeof LoginRoute
  '/login-option': typeof LoginOptionRoute
  '/preview-dokumen': typeof PreviewDokumenRoute
  '/tanda-tangan': typeof TandaTanganRoute
  '/dosen-pendamping/riwayat-persetujuan': typeof DosenPendampingRiwayatPersetujuanRoute
  '/kemahasiswaan/riwayat-persetujuan': typeof KemahasiswaanRiwayatPersetujuanRoute
  '/ketua-departemen/riwayat-persetujuan': typeof KetuaDepartemenRiwayatPersetujuanRoute
  '/ketua-ormawa/preview': typeof KetuaOrmawaPreviewRoute
  '/ketua-ormawa/riwayat-persetujuan': typeof KetuaOrmawaRiwayatPersetujuanRoute
  '/ketua-ormawa/sign': typeof KetuaOrmawaSignRoute
  '/peminjam/reservasi': typeof PeminjamReservasiRoute
  '/senat/riwayat-persetujuan': typeof SenatRiwayatPersetujuanRoute
  '/sumber-daya/manajemen-ruang': typeof SumberDayaManajemenRuangRoute
  '/sumber-daya/riwayat-persetujuan': typeof SumberDayaRiwayatPersetujuanRoute
  '/sumber-daya/tambah-peminjaman': typeof SumberDayaTambahPeminjamanRoute
  '/wadek1/riwayat-persetujuan': typeof Wadek1RiwayatPersetujuanRoute
  '/admin/': typeof AdminIndexRoute
  '/dosen-pendamping/': typeof DosenPendampingIndexRoute
  '/kemahasiswaan/': typeof KemahasiswaanIndexRoute
  '/ketua-departemen/': typeof KetuaDepartemenIndexRoute
  '/ketua-ormawa/': typeof KetuaOrmawaIndexRoute
  '/peminjam/': typeof PeminjamIndexRoute
  '/senat/': typeof SenatIndexRoute
  '/sumber-daya/': typeof SumberDayaIndexRoute
  '/wadek1/': typeof Wadek1IndexRoute
  '/admin/manajemen-ruang/add': typeof AdminManajemenRuangAddRoute
  '/admin/manajemen-ruang/edit': typeof AdminManajemenRuangEditRoute
  '/admin/users/add': typeof AdminUsersAddRoute
  '/admin/users/detail': typeof AdminUsersDetailRoute
  '/admin/users/edit': typeof AdminUsersEditRoute
  '/peminjam/pinjam/detail-tempat': typeof PeminjamPinjamDetailTempatRoute
  '/peminjam/pinjam/edit-dokumen': typeof PeminjamPinjamEditDokumenRoute
  '/peminjam/pinjam/proposal': typeof PeminjamPinjamProposalRoute
  '/peminjam/pinjam/tanda-tangan': typeof PeminjamPinjamTandaTanganRoute
  '/admin/manajemen-ruang': typeof AdminManajemenRuangIndexRoute
  '/admin/peminjaman-ruang': typeof AdminPeminjamanRuangIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/peminjam/pinjam': typeof PeminjamPinjamIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/login-option': typeof LoginOptionRoute
  '/preview-dokumen': typeof PreviewDokumenRoute
  '/tanda-tangan': typeof TandaTanganRoute
  '/dosen-pendamping/riwayat-persetujuan': typeof DosenPendampingRiwayatPersetujuanRoute
  '/kemahasiswaan/riwayat-persetujuan': typeof KemahasiswaanRiwayatPersetujuanRoute
  '/ketua-departemen/riwayat-persetujuan': typeof KetuaDepartemenRiwayatPersetujuanRoute
  '/ketua-ormawa/preview': typeof KetuaOrmawaPreviewRoute
  '/ketua-ormawa/riwayat-persetujuan': typeof KetuaOrmawaRiwayatPersetujuanRoute
  '/ketua-ormawa/sign': typeof KetuaOrmawaSignRoute
  '/peminjam/reservasi': typeof PeminjamReservasiRoute
  '/senat/riwayat-persetujuan': typeof SenatRiwayatPersetujuanRoute
  '/sumber-daya/manajemen-ruang': typeof SumberDayaManajemenRuangRoute
  '/sumber-daya/riwayat-persetujuan': typeof SumberDayaRiwayatPersetujuanRoute
  '/sumber-daya/tambah-peminjaman': typeof SumberDayaTambahPeminjamanRoute
  '/wadek1/riwayat-persetujuan': typeof Wadek1RiwayatPersetujuanRoute
  '/admin': typeof AdminIndexRoute
  '/dosen-pendamping': typeof DosenPendampingIndexRoute
  '/kemahasiswaan': typeof KemahasiswaanIndexRoute
  '/ketua-departemen': typeof KetuaDepartemenIndexRoute
  '/ketua-ormawa': typeof KetuaOrmawaIndexRoute
  '/peminjam': typeof PeminjamIndexRoute
  '/senat': typeof SenatIndexRoute
  '/sumber-daya': typeof SumberDayaIndexRoute
  '/wadek1': typeof Wadek1IndexRoute
  '/admin/manajemen-ruang/add': typeof AdminManajemenRuangAddRoute
  '/admin/manajemen-ruang/edit': typeof AdminManajemenRuangEditRoute
  '/admin/users/add': typeof AdminUsersAddRoute
  '/admin/users/detail': typeof AdminUsersDetailRoute
  '/admin/users/edit': typeof AdminUsersEditRoute
  '/peminjam/pinjam/detail-tempat': typeof PeminjamPinjamDetailTempatRoute
  '/peminjam/pinjam/edit-dokumen': typeof PeminjamPinjamEditDokumenRoute
  '/peminjam/pinjam/proposal': typeof PeminjamPinjamProposalRoute
  '/peminjam/pinjam/tanda-tangan': typeof PeminjamPinjamTandaTanganRoute
  '/admin/manajemen-ruang': typeof AdminManajemenRuangIndexRoute
  '/admin/peminjaman-ruang': typeof AdminPeminjamanRuangIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/peminjam/pinjam': typeof PeminjamPinjamIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/dosen-pendamping': typeof DosenPendampingRouteRouteWithChildren
  '/kemahasiswaan': typeof KemahasiswaanRouteRouteWithChildren
  '/ketua-departemen': typeof KetuaDepartemenRouteRouteWithChildren
  '/ketua-ormawa': typeof KetuaOrmawaRouteRouteWithChildren
  '/peminjam': typeof PeminjamRouteRouteWithChildren
  '/senat': typeof SenatRouteRouteWithChildren
  '/sumber-daya': typeof SumberDayaRouteRouteWithChildren
  '/wadek1': typeof Wadek1RouteRouteWithChildren
  '/login': typeof LoginRoute
  '/login-option': typeof LoginOptionRoute
  '/preview-dokumen': typeof PreviewDokumenRoute
  '/tanda-tangan': typeof TandaTanganRoute
  '/dosen-pendamping/riwayat-persetujuan': typeof DosenPendampingRiwayatPersetujuanRoute
  '/kemahasiswaan/riwayat-persetujuan': typeof KemahasiswaanRiwayatPersetujuanRoute
  '/ketua-departemen/riwayat-persetujuan': typeof KetuaDepartemenRiwayatPersetujuanRoute
  '/ketua-ormawa/preview': typeof KetuaOrmawaPreviewRoute
  '/ketua-ormawa/riwayat-persetujuan': typeof KetuaOrmawaRiwayatPersetujuanRoute
  '/ketua-ormawa/sign': typeof KetuaOrmawaSignRoute
  '/peminjam/reservasi': typeof PeminjamReservasiRoute
  '/senat/riwayat-persetujuan': typeof SenatRiwayatPersetujuanRoute
  '/sumber-daya/manajemen-ruang': typeof SumberDayaManajemenRuangRoute
  '/sumber-daya/riwayat-persetujuan': typeof SumberDayaRiwayatPersetujuanRoute
  '/sumber-daya/tambah-peminjaman': typeof SumberDayaTambahPeminjamanRoute
  '/wadek1/riwayat-persetujuan': typeof Wadek1RiwayatPersetujuanRoute
  '/admin/': typeof AdminIndexRoute
  '/dosen-pendamping/': typeof DosenPendampingIndexRoute
  '/kemahasiswaan/': typeof KemahasiswaanIndexRoute
  '/ketua-departemen/': typeof KetuaDepartemenIndexRoute
  '/ketua-ormawa/': typeof KetuaOrmawaIndexRoute
  '/peminjam/': typeof PeminjamIndexRoute
  '/senat/': typeof SenatIndexRoute
  '/sumber-daya/': typeof SumberDayaIndexRoute
  '/wadek1/': typeof Wadek1IndexRoute
  '/admin/manajemen-ruang/add': typeof AdminManajemenRuangAddRoute
  '/admin/manajemen-ruang/edit': typeof AdminManajemenRuangEditRoute
  '/admin/users/add': typeof AdminUsersAddRoute
  '/admin/users/detail': typeof AdminUsersDetailRoute
  '/admin/users/edit': typeof AdminUsersEditRoute
  '/peminjam/pinjam/detail-tempat': typeof PeminjamPinjamDetailTempatRoute
  '/peminjam/pinjam/edit-dokumen': typeof PeminjamPinjamEditDokumenRoute
  '/peminjam/pinjam/proposal': typeof PeminjamPinjamProposalRoute
  '/peminjam/pinjam/tanda-tangan': typeof PeminjamPinjamTandaTanganRoute
  '/admin/manajemen-ruang/': typeof AdminManajemenRuangIndexRoute
  '/admin/peminjaman-ruang/': typeof AdminPeminjamanRuangIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/peminjam/pinjam/': typeof PeminjamPinjamIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dosen-pendamping'
    | '/kemahasiswaan'
    | '/ketua-departemen'
    | '/ketua-ormawa'
    | '/peminjam'
    | '/senat'
    | '/sumber-daya'
    | '/wadek1'
    | '/login'
    | '/login-option'
    | '/preview-dokumen'
    | '/tanda-tangan'
    | '/dosen-pendamping/riwayat-persetujuan'
    | '/kemahasiswaan/riwayat-persetujuan'
    | '/ketua-departemen/riwayat-persetujuan'
    | '/ketua-ormawa/preview'
    | '/ketua-ormawa/riwayat-persetujuan'
    | '/ketua-ormawa/sign'
    | '/peminjam/reservasi'
    | '/senat/riwayat-persetujuan'
    | '/sumber-daya/manajemen-ruang'
    | '/sumber-daya/riwayat-persetujuan'
    | '/sumber-daya/tambah-peminjaman'
    | '/wadek1/riwayat-persetujuan'
    | '/admin/'
    | '/dosen-pendamping/'
    | '/kemahasiswaan/'
    | '/ketua-departemen/'
    | '/ketua-ormawa/'
    | '/peminjam/'
    | '/senat/'
    | '/sumber-daya/'
    | '/wadek1/'
    | '/admin/manajemen-ruang/add'
    | '/admin/manajemen-ruang/edit'
    | '/admin/users/add'
    | '/admin/users/detail'
    | '/admin/users/edit'
    | '/peminjam/pinjam/detail-tempat'
    | '/peminjam/pinjam/edit-dokumen'
    | '/peminjam/pinjam/proposal'
    | '/peminjam/pinjam/tanda-tangan'
    | '/admin/manajemen-ruang'
    | '/admin/peminjaman-ruang'
    | '/admin/users'
    | '/peminjam/pinjam'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/login-option'
    | '/preview-dokumen'
    | '/tanda-tangan'
    | '/dosen-pendamping/riwayat-persetujuan'
    | '/kemahasiswaan/riwayat-persetujuan'
    | '/ketua-departemen/riwayat-persetujuan'
    | '/ketua-ormawa/preview'
    | '/ketua-ormawa/riwayat-persetujuan'
    | '/ketua-ormawa/sign'
    | '/peminjam/reservasi'
    | '/senat/riwayat-persetujuan'
    | '/sumber-daya/manajemen-ruang'
    | '/sumber-daya/riwayat-persetujuan'
    | '/sumber-daya/tambah-peminjaman'
    | '/wadek1/riwayat-persetujuan'
    | '/admin'
    | '/dosen-pendamping'
    | '/kemahasiswaan'
    | '/ketua-departemen'
    | '/ketua-ormawa'
    | '/peminjam'
    | '/senat'
    | '/sumber-daya'
    | '/wadek1'
    | '/admin/manajemen-ruang/add'
    | '/admin/manajemen-ruang/edit'
    | '/admin/users/add'
    | '/admin/users/detail'
    | '/admin/users/edit'
    | '/peminjam/pinjam/detail-tempat'
    | '/peminjam/pinjam/edit-dokumen'
    | '/peminjam/pinjam/proposal'
    | '/peminjam/pinjam/tanda-tangan'
    | '/admin/manajemen-ruang'
    | '/admin/peminjaman-ruang'
    | '/admin/users'
    | '/peminjam/pinjam'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dosen-pendamping'
    | '/kemahasiswaan'
    | '/ketua-departemen'
    | '/ketua-ormawa'
    | '/peminjam'
    | '/senat'
    | '/sumber-daya'
    | '/wadek1'
    | '/login'
    | '/login-option'
    | '/preview-dokumen'
    | '/tanda-tangan'
    | '/dosen-pendamping/riwayat-persetujuan'
    | '/kemahasiswaan/riwayat-persetujuan'
    | '/ketua-departemen/riwayat-persetujuan'
    | '/ketua-ormawa/preview'
    | '/ketua-ormawa/riwayat-persetujuan'
    | '/ketua-ormawa/sign'
    | '/peminjam/reservasi'
    | '/senat/riwayat-persetujuan'
    | '/sumber-daya/manajemen-ruang'
    | '/sumber-daya/riwayat-persetujuan'
    | '/sumber-daya/tambah-peminjaman'
    | '/wadek1/riwayat-persetujuan'
    | '/admin/'
    | '/dosen-pendamping/'
    | '/kemahasiswaan/'
    | '/ketua-departemen/'
    | '/ketua-ormawa/'
    | '/peminjam/'
    | '/senat/'
    | '/sumber-daya/'
    | '/wadek1/'
    | '/admin/manajemen-ruang/add'
    | '/admin/manajemen-ruang/edit'
    | '/admin/users/add'
    | '/admin/users/detail'
    | '/admin/users/edit'
    | '/peminjam/pinjam/detail-tempat'
    | '/peminjam/pinjam/edit-dokumen'
    | '/peminjam/pinjam/proposal'
    | '/peminjam/pinjam/tanda-tangan'
    | '/admin/manajemen-ruang/'
    | '/admin/peminjaman-ruang/'
    | '/admin/users/'
    | '/peminjam/pinjam/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  DosenPendampingRouteRoute: typeof DosenPendampingRouteRouteWithChildren
  KemahasiswaanRouteRoute: typeof KemahasiswaanRouteRouteWithChildren
  KetuaDepartemenRouteRoute: typeof KetuaDepartemenRouteRouteWithChildren
  KetuaOrmawaRouteRoute: typeof KetuaOrmawaRouteRouteWithChildren
  PeminjamRouteRoute: typeof PeminjamRouteRouteWithChildren
  SenatRouteRoute: typeof SenatRouteRouteWithChildren
  SumberDayaRouteRoute: typeof SumberDayaRouteRouteWithChildren
  Wadek1RouteRoute: typeof Wadek1RouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  LoginOptionRoute: typeof LoginOptionRoute
  PreviewDokumenRoute: typeof PreviewDokumenRoute
  TandaTanganRoute: typeof TandaTanganRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tanda-tangan': {
      id: '/tanda-tangan'
      path: '/tanda-tangan'
      fullPath: '/tanda-tangan'
      preLoaderRoute: typeof TandaTanganRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview-dokumen': {
      id: '/preview-dokumen'
      path: '/preview-dokumen'
      fullPath: '/preview-dokumen'
      preLoaderRoute: typeof PreviewDokumenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login-option': {
      id: '/login-option'
      path: '/login-option'
      fullPath: '/login-option'
      preLoaderRoute: typeof LoginOptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wadek1': {
      id: '/wadek1'
      path: '/wadek1'
      fullPath: '/wadek1'
      preLoaderRoute: typeof Wadek1RouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sumber-daya': {
      id: '/sumber-daya'
      path: '/sumber-daya'
      fullPath: '/sumber-daya'
      preLoaderRoute: typeof SumberDayaRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/senat': {
      id: '/senat'
      path: '/senat'
      fullPath: '/senat'
      preLoaderRoute: typeof SenatRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/peminjam': {
      id: '/peminjam'
      path: '/peminjam'
      fullPath: '/peminjam'
      preLoaderRoute: typeof PeminjamRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ketua-ormawa': {
      id: '/ketua-ormawa'
      path: '/ketua-ormawa'
      fullPath: '/ketua-ormawa'
      preLoaderRoute: typeof KetuaOrmawaRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ketua-departemen': {
      id: '/ketua-departemen'
      path: '/ketua-departemen'
      fullPath: '/ketua-departemen'
      preLoaderRoute: typeof KetuaDepartemenRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kemahasiswaan': {
      id: '/kemahasiswaan'
      path: '/kemahasiswaan'
      fullPath: '/kemahasiswaan'
      preLoaderRoute: typeof KemahasiswaanRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dosen-pendamping': {
      id: '/dosen-pendamping'
      path: '/dosen-pendamping'
      fullPath: '/dosen-pendamping'
      preLoaderRoute: typeof DosenPendampingRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wadek1/': {
      id: '/wadek1/'
      path: '/'
      fullPath: '/wadek1/'
      preLoaderRoute: typeof Wadek1IndexRouteImport
      parentRoute: typeof Wadek1RouteRoute
    }
    '/sumber-daya/': {
      id: '/sumber-daya/'
      path: '/'
      fullPath: '/sumber-daya/'
      preLoaderRoute: typeof SumberDayaIndexRouteImport
      parentRoute: typeof SumberDayaRouteRoute
    }
    '/senat/': {
      id: '/senat/'
      path: '/'
      fullPath: '/senat/'
      preLoaderRoute: typeof SenatIndexRouteImport
      parentRoute: typeof SenatRouteRoute
    }
    '/peminjam/': {
      id: '/peminjam/'
      path: '/'
      fullPath: '/peminjam/'
      preLoaderRoute: typeof PeminjamIndexRouteImport
      parentRoute: typeof PeminjamRouteRoute
    }
    '/ketua-ormawa/': {
      id: '/ketua-ormawa/'
      path: '/'
      fullPath: '/ketua-ormawa/'
      preLoaderRoute: typeof KetuaOrmawaIndexRouteImport
      parentRoute: typeof KetuaOrmawaRouteRoute
    }
    '/ketua-departemen/': {
      id: '/ketua-departemen/'
      path: '/'
      fullPath: '/ketua-departemen/'
      preLoaderRoute: typeof KetuaDepartemenIndexRouteImport
      parentRoute: typeof KetuaDepartemenRouteRoute
    }
    '/kemahasiswaan/': {
      id: '/kemahasiswaan/'
      path: '/'
      fullPath: '/kemahasiswaan/'
      preLoaderRoute: typeof KemahasiswaanIndexRouteImport
      parentRoute: typeof KemahasiswaanRouteRoute
    }
    '/dosen-pendamping/': {
      id: '/dosen-pendamping/'
      path: '/'
      fullPath: '/dosen-pendamping/'
      preLoaderRoute: typeof DosenPendampingIndexRouteImport
      parentRoute: typeof DosenPendampingRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/wadek1/riwayat-persetujuan': {
      id: '/wadek1/riwayat-persetujuan'
      path: '/riwayat-persetujuan'
      fullPath: '/wadek1/riwayat-persetujuan'
      preLoaderRoute: typeof Wadek1RiwayatPersetujuanRouteImport
      parentRoute: typeof Wadek1RouteRoute
    }
    '/sumber-daya/tambah-peminjaman': {
      id: '/sumber-daya/tambah-peminjaman'
      path: '/tambah-peminjaman'
      fullPath: '/sumber-daya/tambah-peminjaman'
      preLoaderRoute: typeof SumberDayaTambahPeminjamanRouteImport
      parentRoute: typeof SumberDayaRouteRoute
    }
    '/sumber-daya/riwayat-persetujuan': {
      id: '/sumber-daya/riwayat-persetujuan'
      path: '/riwayat-persetujuan'
      fullPath: '/sumber-daya/riwayat-persetujuan'
      preLoaderRoute: typeof SumberDayaRiwayatPersetujuanRouteImport
      parentRoute: typeof SumberDayaRouteRoute
    }
    '/sumber-daya/manajemen-ruang': {
      id: '/sumber-daya/manajemen-ruang'
      path: '/manajemen-ruang'
      fullPath: '/sumber-daya/manajemen-ruang'
      preLoaderRoute: typeof SumberDayaManajemenRuangRouteImport
      parentRoute: typeof SumberDayaRouteRoute
    }
    '/senat/riwayat-persetujuan': {
      id: '/senat/riwayat-persetujuan'
      path: '/riwayat-persetujuan'
      fullPath: '/senat/riwayat-persetujuan'
      preLoaderRoute: typeof SenatRiwayatPersetujuanRouteImport
      parentRoute: typeof SenatRouteRoute
    }
    '/peminjam/reservasi': {
      id: '/peminjam/reservasi'
      path: '/reservasi'
      fullPath: '/peminjam/reservasi'
      preLoaderRoute: typeof PeminjamReservasiRouteImport
      parentRoute: typeof PeminjamRouteRoute
    }
    '/ketua-ormawa/sign': {
      id: '/ketua-ormawa/sign'
      path: '/sign'
      fullPath: '/ketua-ormawa/sign'
      preLoaderRoute: typeof KetuaOrmawaSignRouteImport
      parentRoute: typeof KetuaOrmawaRouteRoute
    }
    '/ketua-ormawa/riwayat-persetujuan': {
      id: '/ketua-ormawa/riwayat-persetujuan'
      path: '/riwayat-persetujuan'
      fullPath: '/ketua-ormawa/riwayat-persetujuan'
      preLoaderRoute: typeof KetuaOrmawaRiwayatPersetujuanRouteImport
      parentRoute: typeof KetuaOrmawaRouteRoute
    }
    '/ketua-ormawa/preview': {
      id: '/ketua-ormawa/preview'
      path: '/preview'
      fullPath: '/ketua-ormawa/preview'
      preLoaderRoute: typeof KetuaOrmawaPreviewRouteImport
      parentRoute: typeof KetuaOrmawaRouteRoute
    }
    '/ketua-departemen/riwayat-persetujuan': {
      id: '/ketua-departemen/riwayat-persetujuan'
      path: '/riwayat-persetujuan'
      fullPath: '/ketua-departemen/riwayat-persetujuan'
      preLoaderRoute: typeof KetuaDepartemenRiwayatPersetujuanRouteImport
      parentRoute: typeof KetuaDepartemenRouteRoute
    }
    '/kemahasiswaan/riwayat-persetujuan': {
      id: '/kemahasiswaan/riwayat-persetujuan'
      path: '/riwayat-persetujuan'
      fullPath: '/kemahasiswaan/riwayat-persetujuan'
      preLoaderRoute: typeof KemahasiswaanRiwayatPersetujuanRouteImport
      parentRoute: typeof KemahasiswaanRouteRoute
    }
    '/dosen-pendamping/riwayat-persetujuan': {
      id: '/dosen-pendamping/riwayat-persetujuan'
      path: '/riwayat-persetujuan'
      fullPath: '/dosen-pendamping/riwayat-persetujuan'
      preLoaderRoute: typeof DosenPendampingRiwayatPersetujuanRouteImport
      parentRoute: typeof DosenPendampingRouteRoute
    }
    '/peminjam/pinjam/': {
      id: '/peminjam/pinjam/'
      path: '/pinjam'
      fullPath: '/peminjam/pinjam'
      preLoaderRoute: typeof PeminjamPinjamIndexRouteImport
      parentRoute: typeof PeminjamRouteRoute
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/peminjaman-ruang/': {
      id: '/admin/peminjaman-ruang/'
      path: '/peminjaman-ruang'
      fullPath: '/admin/peminjaman-ruang'
      preLoaderRoute: typeof AdminPeminjamanRuangIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/manajemen-ruang/': {
      id: '/admin/manajemen-ruang/'
      path: '/manajemen-ruang'
      fullPath: '/admin/manajemen-ruang'
      preLoaderRoute: typeof AdminManajemenRuangIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/peminjam/pinjam/tanda-tangan': {
      id: '/peminjam/pinjam/tanda-tangan'
      path: '/pinjam/tanda-tangan'
      fullPath: '/peminjam/pinjam/tanda-tangan'
      preLoaderRoute: typeof PeminjamPinjamTandaTanganRouteImport
      parentRoute: typeof PeminjamRouteRoute
    }
    '/peminjam/pinjam/proposal': {
      id: '/peminjam/pinjam/proposal'
      path: '/pinjam/proposal'
      fullPath: '/peminjam/pinjam/proposal'
      preLoaderRoute: typeof PeminjamPinjamProposalRouteImport
      parentRoute: typeof PeminjamRouteRoute
    }
    '/peminjam/pinjam/edit-dokumen': {
      id: '/peminjam/pinjam/edit-dokumen'
      path: '/pinjam/edit-dokumen'
      fullPath: '/peminjam/pinjam/edit-dokumen'
      preLoaderRoute: typeof PeminjamPinjamEditDokumenRouteImport
      parentRoute: typeof PeminjamRouteRoute
    }
    '/peminjam/pinjam/detail-tempat': {
      id: '/peminjam/pinjam/detail-tempat'
      path: '/pinjam/detail-tempat'
      fullPath: '/peminjam/pinjam/detail-tempat'
      preLoaderRoute: typeof PeminjamPinjamDetailTempatRouteImport
      parentRoute: typeof PeminjamRouteRoute
    }
    '/admin/users/edit': {
      id: '/admin/users/edit'
      path: '/users/edit'
      fullPath: '/admin/users/edit'
      preLoaderRoute: typeof AdminUsersEditRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/users/detail': {
      id: '/admin/users/detail'
      path: '/users/detail'
      fullPath: '/admin/users/detail'
      preLoaderRoute: typeof AdminUsersDetailRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/users/add': {
      id: '/admin/users/add'
      path: '/users/add'
      fullPath: '/admin/users/add'
      preLoaderRoute: typeof AdminUsersAddRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/manajemen-ruang/edit': {
      id: '/admin/manajemen-ruang/edit'
      path: '/manajemen-ruang/edit'
      fullPath: '/admin/manajemen-ruang/edit'
      preLoaderRoute: typeof AdminManajemenRuangEditRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/manajemen-ruang/add': {
      id: '/admin/manajemen-ruang/add'
      path: '/manajemen-ruang/add'
      fullPath: '/admin/manajemen-ruang/add'
      preLoaderRoute: typeof AdminManajemenRuangAddRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminManajemenRuangAddRoute: typeof AdminManajemenRuangAddRoute
  AdminManajemenRuangEditRoute: typeof AdminManajemenRuangEditRoute
  AdminUsersAddRoute: typeof AdminUsersAddRoute
  AdminUsersDetailRoute: typeof AdminUsersDetailRoute
  AdminUsersEditRoute: typeof AdminUsersEditRoute
  AdminManajemenRuangIndexRoute: typeof AdminManajemenRuangIndexRoute
  AdminPeminjamanRuangIndexRoute: typeof AdminPeminjamanRuangIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminManajemenRuangAddRoute: AdminManajemenRuangAddRoute,
  AdminManajemenRuangEditRoute: AdminManajemenRuangEditRoute,
  AdminUsersAddRoute: AdminUsersAddRoute,
  AdminUsersDetailRoute: AdminUsersDetailRoute,
  AdminUsersEditRoute: AdminUsersEditRoute,
  AdminManajemenRuangIndexRoute: AdminManajemenRuangIndexRoute,
  AdminPeminjamanRuangIndexRoute: AdminPeminjamanRuangIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface DosenPendampingRouteRouteChildren {
  DosenPendampingRiwayatPersetujuanRoute: typeof DosenPendampingRiwayatPersetujuanRoute
  DosenPendampingIndexRoute: typeof DosenPendampingIndexRoute
}

const DosenPendampingRouteRouteChildren: DosenPendampingRouteRouteChildren = {
  DosenPendampingRiwayatPersetujuanRoute:
    DosenPendampingRiwayatPersetujuanRoute,
  DosenPendampingIndexRoute: DosenPendampingIndexRoute,
}

const DosenPendampingRouteRouteWithChildren =
  DosenPendampingRouteRoute._addFileChildren(DosenPendampingRouteRouteChildren)

interface KemahasiswaanRouteRouteChildren {
  KemahasiswaanRiwayatPersetujuanRoute: typeof KemahasiswaanRiwayatPersetujuanRoute
  KemahasiswaanIndexRoute: typeof KemahasiswaanIndexRoute
}

const KemahasiswaanRouteRouteChildren: KemahasiswaanRouteRouteChildren = {
  KemahasiswaanRiwayatPersetujuanRoute: KemahasiswaanRiwayatPersetujuanRoute,
  KemahasiswaanIndexRoute: KemahasiswaanIndexRoute,
}

const KemahasiswaanRouteRouteWithChildren =
  KemahasiswaanRouteRoute._addFileChildren(KemahasiswaanRouteRouteChildren)

interface KetuaDepartemenRouteRouteChildren {
  KetuaDepartemenRiwayatPersetujuanRoute: typeof KetuaDepartemenRiwayatPersetujuanRoute
  KetuaDepartemenIndexRoute: typeof KetuaDepartemenIndexRoute
}

const KetuaDepartemenRouteRouteChildren: KetuaDepartemenRouteRouteChildren = {
  KetuaDepartemenRiwayatPersetujuanRoute:
    KetuaDepartemenRiwayatPersetujuanRoute,
  KetuaDepartemenIndexRoute: KetuaDepartemenIndexRoute,
}

const KetuaDepartemenRouteRouteWithChildren =
  KetuaDepartemenRouteRoute._addFileChildren(KetuaDepartemenRouteRouteChildren)

interface KetuaOrmawaRouteRouteChildren {
  KetuaOrmawaPreviewRoute: typeof KetuaOrmawaPreviewRoute
  KetuaOrmawaRiwayatPersetujuanRoute: typeof KetuaOrmawaRiwayatPersetujuanRoute
  KetuaOrmawaSignRoute: typeof KetuaOrmawaSignRoute
  KetuaOrmawaIndexRoute: typeof KetuaOrmawaIndexRoute
}

const KetuaOrmawaRouteRouteChildren: KetuaOrmawaRouteRouteChildren = {
  KetuaOrmawaPreviewRoute: KetuaOrmawaPreviewRoute,
  KetuaOrmawaRiwayatPersetujuanRoute: KetuaOrmawaRiwayatPersetujuanRoute,
  KetuaOrmawaSignRoute: KetuaOrmawaSignRoute,
  KetuaOrmawaIndexRoute: KetuaOrmawaIndexRoute,
}

const KetuaOrmawaRouteRouteWithChildren =
  KetuaOrmawaRouteRoute._addFileChildren(KetuaOrmawaRouteRouteChildren)

interface PeminjamRouteRouteChildren {
  PeminjamReservasiRoute: typeof PeminjamReservasiRoute
  PeminjamIndexRoute: typeof PeminjamIndexRoute
  PeminjamPinjamDetailTempatRoute: typeof PeminjamPinjamDetailTempatRoute
  PeminjamPinjamEditDokumenRoute: typeof PeminjamPinjamEditDokumenRoute
  PeminjamPinjamProposalRoute: typeof PeminjamPinjamProposalRoute
  PeminjamPinjamTandaTanganRoute: typeof PeminjamPinjamTandaTanganRoute
  PeminjamPinjamIndexRoute: typeof PeminjamPinjamIndexRoute
}

const PeminjamRouteRouteChildren: PeminjamRouteRouteChildren = {
  PeminjamReservasiRoute: PeminjamReservasiRoute,
  PeminjamIndexRoute: PeminjamIndexRoute,
  PeminjamPinjamDetailTempatRoute: PeminjamPinjamDetailTempatRoute,
  PeminjamPinjamEditDokumenRoute: PeminjamPinjamEditDokumenRoute,
  PeminjamPinjamProposalRoute: PeminjamPinjamProposalRoute,
  PeminjamPinjamTandaTanganRoute: PeminjamPinjamTandaTanganRoute,
  PeminjamPinjamIndexRoute: PeminjamPinjamIndexRoute,
}

const PeminjamRouteRouteWithChildren = PeminjamRouteRoute._addFileChildren(
  PeminjamRouteRouteChildren,
)

interface SenatRouteRouteChildren {
  SenatRiwayatPersetujuanRoute: typeof SenatRiwayatPersetujuanRoute
  SenatIndexRoute: typeof SenatIndexRoute
}

const SenatRouteRouteChildren: SenatRouteRouteChildren = {
  SenatRiwayatPersetujuanRoute: SenatRiwayatPersetujuanRoute,
  SenatIndexRoute: SenatIndexRoute,
}

const SenatRouteRouteWithChildren = SenatRouteRoute._addFileChildren(
  SenatRouteRouteChildren,
)

interface SumberDayaRouteRouteChildren {
  SumberDayaManajemenRuangRoute: typeof SumberDayaManajemenRuangRoute
  SumberDayaRiwayatPersetujuanRoute: typeof SumberDayaRiwayatPersetujuanRoute
  SumberDayaTambahPeminjamanRoute: typeof SumberDayaTambahPeminjamanRoute
  SumberDayaIndexRoute: typeof SumberDayaIndexRoute
}

const SumberDayaRouteRouteChildren: SumberDayaRouteRouteChildren = {
  SumberDayaManajemenRuangRoute: SumberDayaManajemenRuangRoute,
  SumberDayaRiwayatPersetujuanRoute: SumberDayaRiwayatPersetujuanRoute,
  SumberDayaTambahPeminjamanRoute: SumberDayaTambahPeminjamanRoute,
  SumberDayaIndexRoute: SumberDayaIndexRoute,
}

const SumberDayaRouteRouteWithChildren = SumberDayaRouteRoute._addFileChildren(
  SumberDayaRouteRouteChildren,
)

interface Wadek1RouteRouteChildren {
  Wadek1RiwayatPersetujuanRoute: typeof Wadek1RiwayatPersetujuanRoute
  Wadek1IndexRoute: typeof Wadek1IndexRoute
}

const Wadek1RouteRouteChildren: Wadek1RouteRouteChildren = {
  Wadek1RiwayatPersetujuanRoute: Wadek1RiwayatPersetujuanRoute,
  Wadek1IndexRoute: Wadek1IndexRoute,
}

const Wadek1RouteRouteWithChildren = Wadek1RouteRoute._addFileChildren(
  Wadek1RouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  DosenPendampingRouteRoute: DosenPendampingRouteRouteWithChildren,
  KemahasiswaanRouteRoute: KemahasiswaanRouteRouteWithChildren,
  KetuaDepartemenRouteRoute: KetuaDepartemenRouteRouteWithChildren,
  KetuaOrmawaRouteRoute: KetuaOrmawaRouteRouteWithChildren,
  PeminjamRouteRoute: PeminjamRouteRouteWithChildren,
  SenatRouteRoute: SenatRouteRouteWithChildren,
  SumberDayaRouteRoute: SumberDayaRouteRouteWithChildren,
  Wadek1RouteRoute: Wadek1RouteRouteWithChildren,
  LoginRoute: LoginRoute,
  LoginOptionRoute: LoginOptionRoute,
  PreviewDokumenRoute: PreviewDokumenRoute,
  TandaTanganRoute: TandaTanganRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
