/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginOptionRouteImport } from './routes/login-option'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SumberDayaRouteRouteImport } from './routes/sumber-daya/route'
import { Route as PeminjamRouteRouteImport } from './routes/peminjam/route'
import { Route as KetuaOrmawaRouteRouteImport } from './routes/ketua-ormawa/route'
import { Route as KemahasiswaanRouteRouteImport } from './routes/kemahasiswaan/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Wadek1IndexRouteImport } from './routes/wadek1/index'
import { Route as SumberDayaIndexRouteImport } from './routes/sumber-daya/index'
import { Route as SenatIndexRouteImport } from './routes/senat/index'
import { Route as PeminjamIndexRouteImport } from './routes/peminjam/index'
import { Route as KetuaOrmawaIndexRouteImport } from './routes/ketua-ormawa/index'
import { Route as KetuaDepartemenIndexRouteImport } from './routes/ketua-departemen/index'
import { Route as KemahasiswaanIndexRouteImport } from './routes/kemahasiswaan/index'
import { Route as DosenPendampingIndexRouteImport } from './routes/dosen-pendamping/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as PeminjamReservasiRouteImport } from './routes/peminjam/reservasi'
import { Route as Wadek1ApprovalIndexRouteImport } from './routes/wadek1/approval/index'
import { Route as SumberDayaApprovalIndexRouteImport } from './routes/sumber-daya/approval/index'
import { Route as SenatApprovalIndexRouteImport } from './routes/senat/approval/index'
import { Route as PeminjamPinjamIndexRouteImport } from './routes/peminjam/pinjam/index'
import { Route as KetuaOrmawaApprovalIndexRouteImport } from './routes/ketua-ormawa/approval/index'
import { Route as KetuaDepartemenApprovalIndexRouteImport } from './routes/ketua-departemen/approval/index'
import { Route as KemahasiswaanApprovalIndexRouteImport } from './routes/kemahasiswaan/approval/index'
import { Route as DosenPendampingApprovalIndexRouteImport } from './routes/dosen-pendamping/approval/index'
import { Route as AdminUsersIndexRouteImport } from './routes/admin/users/index'
import { Route as AdminPeminjamanRuangIndexRouteImport } from './routes/admin/peminjaman-ruang/index'
import { Route as AdminManajemenRuangIndexRouteImport } from './routes/admin/manajemen-ruang/index'
import { Route as Wadek1ApprovalEditorRouteImport } from './routes/wadek1/approval/editor'
import { Route as SenatApprovalEditorRouteImport } from './routes/senat/approval/editor'
import { Route as PeminjamPinjamTandaTanganRouteImport } from './routes/peminjam/pinjam/tanda-tangan'
import { Route as PeminjamPinjamProposalRouteImport } from './routes/peminjam/pinjam/proposal'
import { Route as PeminjamPinjamEditDokumenRouteImport } from './routes/peminjam/pinjam/edit-dokumen'
import { Route as PeminjamPinjamDetailTempatRouteImport } from './routes/peminjam/pinjam/detail-tempat'
import { Route as KetuaOrmawaApprovalEditorRouteImport } from './routes/ketua-ormawa/approval/editor'
import { Route as KetuaDepartemenApprovalEditorRouteImport } from './routes/ketua-departemen/approval/editor'
import { Route as KemahasiswaanApprovalEditorRouteImport } from './routes/kemahasiswaan/approval/editor'
import { Route as DosenPendampingApprovalEditorRouteImport } from './routes/dosen-pendamping/approval/editor'
import { Route as AdminUsersEditRouteImport } from './routes/admin/users/edit'
import { Route as AdminUsersDetailRouteImport } from './routes/admin/users/detail'
import { Route as AdminUsersAddRouteImport } from './routes/admin/users/add'
import { Route as AdminManajemenRuangEditRouteImport } from './routes/admin/manajemen-ruang/edit'
import { Route as AdminManajemenRuangAddRouteImport } from './routes/admin/manajemen-ruang/add'

const LoginOptionRoute = LoginOptionRouteImport.update({
  id: '/login-option',
  path: '/login-option',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SumberDayaRouteRoute = SumberDayaRouteRouteImport.update({
  id: '/sumber-daya',
  path: '/sumber-daya',
  getParentRoute: () => rootRouteImport,
} as any)
const PeminjamRouteRoute = PeminjamRouteRouteImport.update({
  id: '/peminjam',
  path: '/peminjam',
  getParentRoute: () => rootRouteImport,
} as any)
const KetuaOrmawaRouteRoute = KetuaOrmawaRouteRouteImport.update({
  id: '/ketua-ormawa',
  path: '/ketua-ormawa',
  getParentRoute: () => rootRouteImport,
} as any)
const KemahasiswaanRouteRoute = KemahasiswaanRouteRouteImport.update({
  id: '/kemahasiswaan',
  path: '/kemahasiswaan',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Wadek1IndexRoute = Wadek1IndexRouteImport.update({
  id: '/wadek1/',
  path: '/wadek1/',
  getParentRoute: () => rootRouteImport,
} as any)
const SumberDayaIndexRoute = SumberDayaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SumberDayaRouteRoute,
} as any)
const SenatIndexRoute = SenatIndexRouteImport.update({
  id: '/senat/',
  path: '/senat/',
  getParentRoute: () => rootRouteImport,
} as any)
const PeminjamIndexRoute = PeminjamIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PeminjamRouteRoute,
} as any)
const KetuaOrmawaIndexRoute = KetuaOrmawaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => KetuaOrmawaRouteRoute,
} as any)
const KetuaDepartemenIndexRoute = KetuaDepartemenIndexRouteImport.update({
  id: '/ketua-departemen/',
  path: '/ketua-departemen/',
  getParentRoute: () => rootRouteImport,
} as any)
const KemahasiswaanIndexRoute = KemahasiswaanIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => KemahasiswaanRouteRoute,
} as any)
const DosenPendampingIndexRoute = DosenPendampingIndexRouteImport.update({
  id: '/dosen-pendamping/',
  path: '/dosen-pendamping/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const PeminjamReservasiRoute = PeminjamReservasiRouteImport.update({
  id: '/reservasi',
  path: '/reservasi',
  getParentRoute: () => PeminjamRouteRoute,
} as any)
const Wadek1ApprovalIndexRoute = Wadek1ApprovalIndexRouteImport.update({
  id: '/wadek1/approval/',
  path: '/wadek1/approval/',
  getParentRoute: () => rootRouteImport,
} as any)
const SumberDayaApprovalIndexRoute = SumberDayaApprovalIndexRouteImport.update({
  id: '/approval/',
  path: '/approval/',
  getParentRoute: () => SumberDayaRouteRoute,
} as any)
const SenatApprovalIndexRoute = SenatApprovalIndexRouteImport.update({
  id: '/senat/approval/',
  path: '/senat/approval/',
  getParentRoute: () => rootRouteImport,
} as any)
const PeminjamPinjamIndexRoute = PeminjamPinjamIndexRouteImport.update({
  id: '/pinjam/',
  path: '/pinjam/',
  getParentRoute: () => PeminjamRouteRoute,
} as any)
const KetuaOrmawaApprovalIndexRoute =
  KetuaOrmawaApprovalIndexRouteImport.update({
    id: '/approval/',
    path: '/approval/',
    getParentRoute: () => KetuaOrmawaRouteRoute,
  } as any)
const KetuaDepartemenApprovalIndexRoute =
  KetuaDepartemenApprovalIndexRouteImport.update({
    id: '/ketua-departemen/approval/',
    path: '/ketua-departemen/approval/',
    getParentRoute: () => rootRouteImport,
  } as any)
const KemahasiswaanApprovalIndexRoute =
  KemahasiswaanApprovalIndexRouteImport.update({
    id: '/approval/',
    path: '/approval/',
    getParentRoute: () => KemahasiswaanRouteRoute,
  } as any)
const DosenPendampingApprovalIndexRoute =
  DosenPendampingApprovalIndexRouteImport.update({
    id: '/dosen-pendamping/approval/',
    path: '/dosen-pendamping/approval/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPeminjamanRuangIndexRoute =
  AdminPeminjamanRuangIndexRouteImport.update({
    id: '/peminjaman-ruang/',
    path: '/peminjaman-ruang/',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminManajemenRuangIndexRoute =
  AdminManajemenRuangIndexRouteImport.update({
    id: '/manajemen-ruang/',
    path: '/manajemen-ruang/',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const Wadek1ApprovalEditorRoute = Wadek1ApprovalEditorRouteImport.update({
  id: '/wadek1/approval/editor',
  path: '/wadek1/approval/editor',
  getParentRoute: () => rootRouteImport,
} as any)
const SenatApprovalEditorRoute = SenatApprovalEditorRouteImport.update({
  id: '/senat/approval/editor',
  path: '/senat/approval/editor',
  getParentRoute: () => rootRouteImport,
} as any)
const PeminjamPinjamTandaTanganRoute =
  PeminjamPinjamTandaTanganRouteImport.update({
    id: '/pinjam/tanda-tangan',
    path: '/pinjam/tanda-tangan',
    getParentRoute: () => PeminjamRouteRoute,
  } as any)
const PeminjamPinjamProposalRoute = PeminjamPinjamProposalRouteImport.update({
  id: '/pinjam/proposal',
  path: '/pinjam/proposal',
  getParentRoute: () => PeminjamRouteRoute,
} as any)
const PeminjamPinjamEditDokumenRoute =
  PeminjamPinjamEditDokumenRouteImport.update({
    id: '/pinjam/edit-dokumen',
    path: '/pinjam/edit-dokumen',
    getParentRoute: () => PeminjamRouteRoute,
  } as any)
const PeminjamPinjamDetailTempatRoute =
  PeminjamPinjamDetailTempatRouteImport.update({
    id: '/pinjam/detail-tempat',
    path: '/pinjam/detail-tempat',
    getParentRoute: () => PeminjamRouteRoute,
  } as any)
const KetuaOrmawaApprovalEditorRoute =
  KetuaOrmawaApprovalEditorRouteImport.update({
    id: '/approval/editor',
    path: '/approval/editor',
    getParentRoute: () => KetuaOrmawaRouteRoute,
  } as any)
const KetuaDepartemenApprovalEditorRoute =
  KetuaDepartemenApprovalEditorRouteImport.update({
    id: '/ketua-departemen/approval/editor',
    path: '/ketua-departemen/approval/editor',
    getParentRoute: () => rootRouteImport,
  } as any)
const KemahasiswaanApprovalEditorRoute =
  KemahasiswaanApprovalEditorRouteImport.update({
    id: '/approval/editor',
    path: '/approval/editor',
    getParentRoute: () => KemahasiswaanRouteRoute,
  } as any)
const DosenPendampingApprovalEditorRoute =
  DosenPendampingApprovalEditorRouteImport.update({
    id: '/dosen-pendamping/approval/editor',
    path: '/dosen-pendamping/approval/editor',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminUsersEditRoute = AdminUsersEditRouteImport.update({
  id: '/users/edit',
  path: '/users/edit',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUsersDetailRoute = AdminUsersDetailRouteImport.update({
  id: '/users/detail',
  path: '/users/detail',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUsersAddRoute = AdminUsersAddRouteImport.update({
  id: '/users/add',
  path: '/users/add',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminManajemenRuangEditRoute = AdminManajemenRuangEditRouteImport.update({
  id: '/manajemen-ruang/edit',
  path: '/manajemen-ruang/edit',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminManajemenRuangAddRoute = AdminManajemenRuangAddRouteImport.update({
  id: '/manajemen-ruang/add',
  path: '/manajemen-ruang/add',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/kemahasiswaan': typeof KemahasiswaanRouteRouteWithChildren
  '/ketua-ormawa': typeof KetuaOrmawaRouteRouteWithChildren
  '/peminjam': typeof PeminjamRouteRouteWithChildren
  '/sumber-daya': typeof SumberDayaRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/login-option': typeof LoginOptionRoute
  '/peminjam/reservasi': typeof PeminjamReservasiRoute
  '/admin/': typeof AdminIndexRoute
  '/dosen-pendamping': typeof DosenPendampingIndexRoute
  '/kemahasiswaan/': typeof KemahasiswaanIndexRoute
  '/ketua-departemen': typeof KetuaDepartemenIndexRoute
  '/ketua-ormawa/': typeof KetuaOrmawaIndexRoute
  '/peminjam/': typeof PeminjamIndexRoute
  '/senat': typeof SenatIndexRoute
  '/sumber-daya/': typeof SumberDayaIndexRoute
  '/wadek1': typeof Wadek1IndexRoute
  '/admin/manajemen-ruang/add': typeof AdminManajemenRuangAddRoute
  '/admin/manajemen-ruang/edit': typeof AdminManajemenRuangEditRoute
  '/admin/users/add': typeof AdminUsersAddRoute
  '/admin/users/detail': typeof AdminUsersDetailRoute
  '/admin/users/edit': typeof AdminUsersEditRoute
  '/dosen-pendamping/approval/editor': typeof DosenPendampingApprovalEditorRoute
  '/kemahasiswaan/approval/editor': typeof KemahasiswaanApprovalEditorRoute
  '/ketua-departemen/approval/editor': typeof KetuaDepartemenApprovalEditorRoute
  '/ketua-ormawa/approval/editor': typeof KetuaOrmawaApprovalEditorRoute
  '/peminjam/pinjam/detail-tempat': typeof PeminjamPinjamDetailTempatRoute
  '/peminjam/pinjam/edit-dokumen': typeof PeminjamPinjamEditDokumenRoute
  '/peminjam/pinjam/proposal': typeof PeminjamPinjamProposalRoute
  '/peminjam/pinjam/tanda-tangan': typeof PeminjamPinjamTandaTanganRoute
  '/senat/approval/editor': typeof SenatApprovalEditorRoute
  '/wadek1/approval/editor': typeof Wadek1ApprovalEditorRoute
  '/admin/manajemen-ruang': typeof AdminManajemenRuangIndexRoute
  '/admin/peminjaman-ruang': typeof AdminPeminjamanRuangIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/dosen-pendamping/approval': typeof DosenPendampingApprovalIndexRoute
  '/kemahasiswaan/approval': typeof KemahasiswaanApprovalIndexRoute
  '/ketua-departemen/approval': typeof KetuaDepartemenApprovalIndexRoute
  '/ketua-ormawa/approval': typeof KetuaOrmawaApprovalIndexRoute
  '/peminjam/pinjam': typeof PeminjamPinjamIndexRoute
  '/senat/approval': typeof SenatApprovalIndexRoute
  '/sumber-daya/approval': typeof SumberDayaApprovalIndexRoute
  '/wadek1/approval': typeof Wadek1ApprovalIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/login-option': typeof LoginOptionRoute
  '/peminjam/reservasi': typeof PeminjamReservasiRoute
  '/admin': typeof AdminIndexRoute
  '/dosen-pendamping': typeof DosenPendampingIndexRoute
  '/kemahasiswaan': typeof KemahasiswaanIndexRoute
  '/ketua-departemen': typeof KetuaDepartemenIndexRoute
  '/ketua-ormawa': typeof KetuaOrmawaIndexRoute
  '/peminjam': typeof PeminjamIndexRoute
  '/senat': typeof SenatIndexRoute
  '/sumber-daya': typeof SumberDayaIndexRoute
  '/wadek1': typeof Wadek1IndexRoute
  '/admin/manajemen-ruang/add': typeof AdminManajemenRuangAddRoute
  '/admin/manajemen-ruang/edit': typeof AdminManajemenRuangEditRoute
  '/admin/users/add': typeof AdminUsersAddRoute
  '/admin/users/detail': typeof AdminUsersDetailRoute
  '/admin/users/edit': typeof AdminUsersEditRoute
  '/dosen-pendamping/approval/editor': typeof DosenPendampingApprovalEditorRoute
  '/kemahasiswaan/approval/editor': typeof KemahasiswaanApprovalEditorRoute
  '/ketua-departemen/approval/editor': typeof KetuaDepartemenApprovalEditorRoute
  '/ketua-ormawa/approval/editor': typeof KetuaOrmawaApprovalEditorRoute
  '/peminjam/pinjam/detail-tempat': typeof PeminjamPinjamDetailTempatRoute
  '/peminjam/pinjam/edit-dokumen': typeof PeminjamPinjamEditDokumenRoute
  '/peminjam/pinjam/proposal': typeof PeminjamPinjamProposalRoute
  '/peminjam/pinjam/tanda-tangan': typeof PeminjamPinjamTandaTanganRoute
  '/senat/approval/editor': typeof SenatApprovalEditorRoute
  '/wadek1/approval/editor': typeof Wadek1ApprovalEditorRoute
  '/admin/manajemen-ruang': typeof AdminManajemenRuangIndexRoute
  '/admin/peminjaman-ruang': typeof AdminPeminjamanRuangIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/dosen-pendamping/approval': typeof DosenPendampingApprovalIndexRoute
  '/kemahasiswaan/approval': typeof KemahasiswaanApprovalIndexRoute
  '/ketua-departemen/approval': typeof KetuaDepartemenApprovalIndexRoute
  '/ketua-ormawa/approval': typeof KetuaOrmawaApprovalIndexRoute
  '/peminjam/pinjam': typeof PeminjamPinjamIndexRoute
  '/senat/approval': typeof SenatApprovalIndexRoute
  '/sumber-daya/approval': typeof SumberDayaApprovalIndexRoute
  '/wadek1/approval': typeof Wadek1ApprovalIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/kemahasiswaan': typeof KemahasiswaanRouteRouteWithChildren
  '/ketua-ormawa': typeof KetuaOrmawaRouteRouteWithChildren
  '/peminjam': typeof PeminjamRouteRouteWithChildren
  '/sumber-daya': typeof SumberDayaRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/login-option': typeof LoginOptionRoute
  '/peminjam/reservasi': typeof PeminjamReservasiRoute
  '/admin/': typeof AdminIndexRoute
  '/dosen-pendamping/': typeof DosenPendampingIndexRoute
  '/kemahasiswaan/': typeof KemahasiswaanIndexRoute
  '/ketua-departemen/': typeof KetuaDepartemenIndexRoute
  '/ketua-ormawa/': typeof KetuaOrmawaIndexRoute
  '/peminjam/': typeof PeminjamIndexRoute
  '/senat/': typeof SenatIndexRoute
  '/sumber-daya/': typeof SumberDayaIndexRoute
  '/wadek1/': typeof Wadek1IndexRoute
  '/admin/manajemen-ruang/add': typeof AdminManajemenRuangAddRoute
  '/admin/manajemen-ruang/edit': typeof AdminManajemenRuangEditRoute
  '/admin/users/add': typeof AdminUsersAddRoute
  '/admin/users/detail': typeof AdminUsersDetailRoute
  '/admin/users/edit': typeof AdminUsersEditRoute
  '/dosen-pendamping/approval/editor': typeof DosenPendampingApprovalEditorRoute
  '/kemahasiswaan/approval/editor': typeof KemahasiswaanApprovalEditorRoute
  '/ketua-departemen/approval/editor': typeof KetuaDepartemenApprovalEditorRoute
  '/ketua-ormawa/approval/editor': typeof KetuaOrmawaApprovalEditorRoute
  '/peminjam/pinjam/detail-tempat': typeof PeminjamPinjamDetailTempatRoute
  '/peminjam/pinjam/edit-dokumen': typeof PeminjamPinjamEditDokumenRoute
  '/peminjam/pinjam/proposal': typeof PeminjamPinjamProposalRoute
  '/peminjam/pinjam/tanda-tangan': typeof PeminjamPinjamTandaTanganRoute
  '/senat/approval/editor': typeof SenatApprovalEditorRoute
  '/wadek1/approval/editor': typeof Wadek1ApprovalEditorRoute
  '/admin/manajemen-ruang/': typeof AdminManajemenRuangIndexRoute
  '/admin/peminjaman-ruang/': typeof AdminPeminjamanRuangIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/dosen-pendamping/approval/': typeof DosenPendampingApprovalIndexRoute
  '/kemahasiswaan/approval/': typeof KemahasiswaanApprovalIndexRoute
  '/ketua-departemen/approval/': typeof KetuaDepartemenApprovalIndexRoute
  '/ketua-ormawa/approval/': typeof KetuaOrmawaApprovalIndexRoute
  '/peminjam/pinjam/': typeof PeminjamPinjamIndexRoute
  '/senat/approval/': typeof SenatApprovalIndexRoute
  '/sumber-daya/approval/': typeof SumberDayaApprovalIndexRoute
  '/wadek1/approval/': typeof Wadek1ApprovalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/kemahasiswaan'
    | '/ketua-ormawa'
    | '/peminjam'
    | '/sumber-daya'
    | '/login'
    | '/login-option'
    | '/peminjam/reservasi'
    | '/admin/'
    | '/dosen-pendamping'
    | '/kemahasiswaan/'
    | '/ketua-departemen'
    | '/ketua-ormawa/'
    | '/peminjam/'
    | '/senat'
    | '/sumber-daya/'
    | '/wadek1'
    | '/admin/manajemen-ruang/add'
    | '/admin/manajemen-ruang/edit'
    | '/admin/users/add'
    | '/admin/users/detail'
    | '/admin/users/edit'
    | '/dosen-pendamping/approval/editor'
    | '/kemahasiswaan/approval/editor'
    | '/ketua-departemen/approval/editor'
    | '/ketua-ormawa/approval/editor'
    | '/peminjam/pinjam/detail-tempat'
    | '/peminjam/pinjam/edit-dokumen'
    | '/peminjam/pinjam/proposal'
    | '/peminjam/pinjam/tanda-tangan'
    | '/senat/approval/editor'
    | '/wadek1/approval/editor'
    | '/admin/manajemen-ruang'
    | '/admin/peminjaman-ruang'
    | '/admin/users'
    | '/dosen-pendamping/approval'
    | '/kemahasiswaan/approval'
    | '/ketua-departemen/approval'
    | '/ketua-ormawa/approval'
    | '/peminjam/pinjam'
    | '/senat/approval'
    | '/sumber-daya/approval'
    | '/wadek1/approval'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/login-option'
    | '/peminjam/reservasi'
    | '/admin'
    | '/dosen-pendamping'
    | '/kemahasiswaan'
    | '/ketua-departemen'
    | '/ketua-ormawa'
    | '/peminjam'
    | '/senat'
    | '/sumber-daya'
    | '/wadek1'
    | '/admin/manajemen-ruang/add'
    | '/admin/manajemen-ruang/edit'
    | '/admin/users/add'
    | '/admin/users/detail'
    | '/admin/users/edit'
    | '/dosen-pendamping/approval/editor'
    | '/kemahasiswaan/approval/editor'
    | '/ketua-departemen/approval/editor'
    | '/ketua-ormawa/approval/editor'
    | '/peminjam/pinjam/detail-tempat'
    | '/peminjam/pinjam/edit-dokumen'
    | '/peminjam/pinjam/proposal'
    | '/peminjam/pinjam/tanda-tangan'
    | '/senat/approval/editor'
    | '/wadek1/approval/editor'
    | '/admin/manajemen-ruang'
    | '/admin/peminjaman-ruang'
    | '/admin/users'
    | '/dosen-pendamping/approval'
    | '/kemahasiswaan/approval'
    | '/ketua-departemen/approval'
    | '/ketua-ormawa/approval'
    | '/peminjam/pinjam'
    | '/senat/approval'
    | '/sumber-daya/approval'
    | '/wadek1/approval'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/kemahasiswaan'
    | '/ketua-ormawa'
    | '/peminjam'
    | '/sumber-daya'
    | '/login'
    | '/login-option'
    | '/peminjam/reservasi'
    | '/admin/'
    | '/dosen-pendamping/'
    | '/kemahasiswaan/'
    | '/ketua-departemen/'
    | '/ketua-ormawa/'
    | '/peminjam/'
    | '/senat/'
    | '/sumber-daya/'
    | '/wadek1/'
    | '/admin/manajemen-ruang/add'
    | '/admin/manajemen-ruang/edit'
    | '/admin/users/add'
    | '/admin/users/detail'
    | '/admin/users/edit'
    | '/dosen-pendamping/approval/editor'
    | '/kemahasiswaan/approval/editor'
    | '/ketua-departemen/approval/editor'
    | '/ketua-ormawa/approval/editor'
    | '/peminjam/pinjam/detail-tempat'
    | '/peminjam/pinjam/edit-dokumen'
    | '/peminjam/pinjam/proposal'
    | '/peminjam/pinjam/tanda-tangan'
    | '/senat/approval/editor'
    | '/wadek1/approval/editor'
    | '/admin/manajemen-ruang/'
    | '/admin/peminjaman-ruang/'
    | '/admin/users/'
    | '/dosen-pendamping/approval/'
    | '/kemahasiswaan/approval/'
    | '/ketua-departemen/approval/'
    | '/ketua-ormawa/approval/'
    | '/peminjam/pinjam/'
    | '/senat/approval/'
    | '/sumber-daya/approval/'
    | '/wadek1/approval/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  KemahasiswaanRouteRoute: typeof KemahasiswaanRouteRouteWithChildren
  KetuaOrmawaRouteRoute: typeof KetuaOrmawaRouteRouteWithChildren
  PeminjamRouteRoute: typeof PeminjamRouteRouteWithChildren
  SumberDayaRouteRoute: typeof SumberDayaRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  LoginOptionRoute: typeof LoginOptionRoute
  DosenPendampingIndexRoute: typeof DosenPendampingIndexRoute
  KetuaDepartemenIndexRoute: typeof KetuaDepartemenIndexRoute
  SenatIndexRoute: typeof SenatIndexRoute
  Wadek1IndexRoute: typeof Wadek1IndexRoute
  DosenPendampingApprovalEditorRoute: typeof DosenPendampingApprovalEditorRoute
  KetuaDepartemenApprovalEditorRoute: typeof KetuaDepartemenApprovalEditorRoute
  SenatApprovalEditorRoute: typeof SenatApprovalEditorRoute
  Wadek1ApprovalEditorRoute: typeof Wadek1ApprovalEditorRoute
  DosenPendampingApprovalIndexRoute: typeof DosenPendampingApprovalIndexRoute
  KetuaDepartemenApprovalIndexRoute: typeof KetuaDepartemenApprovalIndexRoute
  SenatApprovalIndexRoute: typeof SenatApprovalIndexRoute
  Wadek1ApprovalIndexRoute: typeof Wadek1ApprovalIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login-option': {
      id: '/login-option'
      path: '/login-option'
      fullPath: '/login-option'
      preLoaderRoute: typeof LoginOptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sumber-daya': {
      id: '/sumber-daya'
      path: '/sumber-daya'
      fullPath: '/sumber-daya'
      preLoaderRoute: typeof SumberDayaRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/peminjam': {
      id: '/peminjam'
      path: '/peminjam'
      fullPath: '/peminjam'
      preLoaderRoute: typeof PeminjamRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ketua-ormawa': {
      id: '/ketua-ormawa'
      path: '/ketua-ormawa'
      fullPath: '/ketua-ormawa'
      preLoaderRoute: typeof KetuaOrmawaRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kemahasiswaan': {
      id: '/kemahasiswaan'
      path: '/kemahasiswaan'
      fullPath: '/kemahasiswaan'
      preLoaderRoute: typeof KemahasiswaanRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wadek1/': {
      id: '/wadek1/'
      path: '/wadek1'
      fullPath: '/wadek1'
      preLoaderRoute: typeof Wadek1IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sumber-daya/': {
      id: '/sumber-daya/'
      path: '/'
      fullPath: '/sumber-daya/'
      preLoaderRoute: typeof SumberDayaIndexRouteImport
      parentRoute: typeof SumberDayaRouteRoute
    }
    '/senat/': {
      id: '/senat/'
      path: '/senat'
      fullPath: '/senat'
      preLoaderRoute: typeof SenatIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/peminjam/': {
      id: '/peminjam/'
      path: '/'
      fullPath: '/peminjam/'
      preLoaderRoute: typeof PeminjamIndexRouteImport
      parentRoute: typeof PeminjamRouteRoute
    }
    '/ketua-ormawa/': {
      id: '/ketua-ormawa/'
      path: '/'
      fullPath: '/ketua-ormawa/'
      preLoaderRoute: typeof KetuaOrmawaIndexRouteImport
      parentRoute: typeof KetuaOrmawaRouteRoute
    }
    '/ketua-departemen/': {
      id: '/ketua-departemen/'
      path: '/ketua-departemen'
      fullPath: '/ketua-departemen'
      preLoaderRoute: typeof KetuaDepartemenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kemahasiswaan/': {
      id: '/kemahasiswaan/'
      path: '/'
      fullPath: '/kemahasiswaan/'
      preLoaderRoute: typeof KemahasiswaanIndexRouteImport
      parentRoute: typeof KemahasiswaanRouteRoute
    }
    '/dosen-pendamping/': {
      id: '/dosen-pendamping/'
      path: '/dosen-pendamping'
      fullPath: '/dosen-pendamping'
      preLoaderRoute: typeof DosenPendampingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/peminjam/reservasi': {
      id: '/peminjam/reservasi'
      path: '/reservasi'
      fullPath: '/peminjam/reservasi'
      preLoaderRoute: typeof PeminjamReservasiRouteImport
      parentRoute: typeof PeminjamRouteRoute
    }
    '/wadek1/approval/': {
      id: '/wadek1/approval/'
      path: '/wadek1/approval'
      fullPath: '/wadek1/approval'
      preLoaderRoute: typeof Wadek1ApprovalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sumber-daya/approval/': {
      id: '/sumber-daya/approval/'
      path: '/approval'
      fullPath: '/sumber-daya/approval'
      preLoaderRoute: typeof SumberDayaApprovalIndexRouteImport
      parentRoute: typeof SumberDayaRouteRoute
    }
    '/senat/approval/': {
      id: '/senat/approval/'
      path: '/senat/approval'
      fullPath: '/senat/approval'
      preLoaderRoute: typeof SenatApprovalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/peminjam/pinjam/': {
      id: '/peminjam/pinjam/'
      path: '/pinjam'
      fullPath: '/peminjam/pinjam'
      preLoaderRoute: typeof PeminjamPinjamIndexRouteImport
      parentRoute: typeof PeminjamRouteRoute
    }
    '/ketua-ormawa/approval/': {
      id: '/ketua-ormawa/approval/'
      path: '/approval'
      fullPath: '/ketua-ormawa/approval'
      preLoaderRoute: typeof KetuaOrmawaApprovalIndexRouteImport
      parentRoute: typeof KetuaOrmawaRouteRoute
    }
    '/ketua-departemen/approval/': {
      id: '/ketua-departemen/approval/'
      path: '/ketua-departemen/approval'
      fullPath: '/ketua-departemen/approval'
      preLoaderRoute: typeof KetuaDepartemenApprovalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kemahasiswaan/approval/': {
      id: '/kemahasiswaan/approval/'
      path: '/approval'
      fullPath: '/kemahasiswaan/approval'
      preLoaderRoute: typeof KemahasiswaanApprovalIndexRouteImport
      parentRoute: typeof KemahasiswaanRouteRoute
    }
    '/dosen-pendamping/approval/': {
      id: '/dosen-pendamping/approval/'
      path: '/dosen-pendamping/approval'
      fullPath: '/dosen-pendamping/approval'
      preLoaderRoute: typeof DosenPendampingApprovalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/peminjaman-ruang/': {
      id: '/admin/peminjaman-ruang/'
      path: '/peminjaman-ruang'
      fullPath: '/admin/peminjaman-ruang'
      preLoaderRoute: typeof AdminPeminjamanRuangIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/manajemen-ruang/': {
      id: '/admin/manajemen-ruang/'
      path: '/manajemen-ruang'
      fullPath: '/admin/manajemen-ruang'
      preLoaderRoute: typeof AdminManajemenRuangIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/wadek1/approval/editor': {
      id: '/wadek1/approval/editor'
      path: '/wadek1/approval/editor'
      fullPath: '/wadek1/approval/editor'
      preLoaderRoute: typeof Wadek1ApprovalEditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/senat/approval/editor': {
      id: '/senat/approval/editor'
      path: '/senat/approval/editor'
      fullPath: '/senat/approval/editor'
      preLoaderRoute: typeof SenatApprovalEditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/peminjam/pinjam/tanda-tangan': {
      id: '/peminjam/pinjam/tanda-tangan'
      path: '/pinjam/tanda-tangan'
      fullPath: '/peminjam/pinjam/tanda-tangan'
      preLoaderRoute: typeof PeminjamPinjamTandaTanganRouteImport
      parentRoute: typeof PeminjamRouteRoute
    }
    '/peminjam/pinjam/proposal': {
      id: '/peminjam/pinjam/proposal'
      path: '/pinjam/proposal'
      fullPath: '/peminjam/pinjam/proposal'
      preLoaderRoute: typeof PeminjamPinjamProposalRouteImport
      parentRoute: typeof PeminjamRouteRoute
    }
    '/peminjam/pinjam/edit-dokumen': {
      id: '/peminjam/pinjam/edit-dokumen'
      path: '/pinjam/edit-dokumen'
      fullPath: '/peminjam/pinjam/edit-dokumen'
      preLoaderRoute: typeof PeminjamPinjamEditDokumenRouteImport
      parentRoute: typeof PeminjamRouteRoute
    }
    '/peminjam/pinjam/detail-tempat': {
      id: '/peminjam/pinjam/detail-tempat'
      path: '/pinjam/detail-tempat'
      fullPath: '/peminjam/pinjam/detail-tempat'
      preLoaderRoute: typeof PeminjamPinjamDetailTempatRouteImport
      parentRoute: typeof PeminjamRouteRoute
    }
    '/ketua-ormawa/approval/editor': {
      id: '/ketua-ormawa/approval/editor'
      path: '/approval/editor'
      fullPath: '/ketua-ormawa/approval/editor'
      preLoaderRoute: typeof KetuaOrmawaApprovalEditorRouteImport
      parentRoute: typeof KetuaOrmawaRouteRoute
    }
    '/ketua-departemen/approval/editor': {
      id: '/ketua-departemen/approval/editor'
      path: '/ketua-departemen/approval/editor'
      fullPath: '/ketua-departemen/approval/editor'
      preLoaderRoute: typeof KetuaDepartemenApprovalEditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kemahasiswaan/approval/editor': {
      id: '/kemahasiswaan/approval/editor'
      path: '/approval/editor'
      fullPath: '/kemahasiswaan/approval/editor'
      preLoaderRoute: typeof KemahasiswaanApprovalEditorRouteImport
      parentRoute: typeof KemahasiswaanRouteRoute
    }
    '/dosen-pendamping/approval/editor': {
      id: '/dosen-pendamping/approval/editor'
      path: '/dosen-pendamping/approval/editor'
      fullPath: '/dosen-pendamping/approval/editor'
      preLoaderRoute: typeof DosenPendampingApprovalEditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users/edit': {
      id: '/admin/users/edit'
      path: '/users/edit'
      fullPath: '/admin/users/edit'
      preLoaderRoute: typeof AdminUsersEditRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/users/detail': {
      id: '/admin/users/detail'
      path: '/users/detail'
      fullPath: '/admin/users/detail'
      preLoaderRoute: typeof AdminUsersDetailRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/users/add': {
      id: '/admin/users/add'
      path: '/users/add'
      fullPath: '/admin/users/add'
      preLoaderRoute: typeof AdminUsersAddRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/manajemen-ruang/edit': {
      id: '/admin/manajemen-ruang/edit'
      path: '/manajemen-ruang/edit'
      fullPath: '/admin/manajemen-ruang/edit'
      preLoaderRoute: typeof AdminManajemenRuangEditRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/manajemen-ruang/add': {
      id: '/admin/manajemen-ruang/add'
      path: '/manajemen-ruang/add'
      fullPath: '/admin/manajemen-ruang/add'
      preLoaderRoute: typeof AdminManajemenRuangAddRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminManajemenRuangAddRoute: typeof AdminManajemenRuangAddRoute
  AdminManajemenRuangEditRoute: typeof AdminManajemenRuangEditRoute
  AdminUsersAddRoute: typeof AdminUsersAddRoute
  AdminUsersDetailRoute: typeof AdminUsersDetailRoute
  AdminUsersEditRoute: typeof AdminUsersEditRoute
  AdminManajemenRuangIndexRoute: typeof AdminManajemenRuangIndexRoute
  AdminPeminjamanRuangIndexRoute: typeof AdminPeminjamanRuangIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminManajemenRuangAddRoute: AdminManajemenRuangAddRoute,
  AdminManajemenRuangEditRoute: AdminManajemenRuangEditRoute,
  AdminUsersAddRoute: AdminUsersAddRoute,
  AdminUsersDetailRoute: AdminUsersDetailRoute,
  AdminUsersEditRoute: AdminUsersEditRoute,
  AdminManajemenRuangIndexRoute: AdminManajemenRuangIndexRoute,
  AdminPeminjamanRuangIndexRoute: AdminPeminjamanRuangIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface KemahasiswaanRouteRouteChildren {
  KemahasiswaanIndexRoute: typeof KemahasiswaanIndexRoute
  KemahasiswaanApprovalEditorRoute: typeof KemahasiswaanApprovalEditorRoute
  KemahasiswaanApprovalIndexRoute: typeof KemahasiswaanApprovalIndexRoute
}

const KemahasiswaanRouteRouteChildren: KemahasiswaanRouteRouteChildren = {
  KemahasiswaanIndexRoute: KemahasiswaanIndexRoute,
  KemahasiswaanApprovalEditorRoute: KemahasiswaanApprovalEditorRoute,
  KemahasiswaanApprovalIndexRoute: KemahasiswaanApprovalIndexRoute,
}

const KemahasiswaanRouteRouteWithChildren =
  KemahasiswaanRouteRoute._addFileChildren(KemahasiswaanRouteRouteChildren)

interface KetuaOrmawaRouteRouteChildren {
  KetuaOrmawaIndexRoute: typeof KetuaOrmawaIndexRoute
  KetuaOrmawaApprovalEditorRoute: typeof KetuaOrmawaApprovalEditorRoute
  KetuaOrmawaApprovalIndexRoute: typeof KetuaOrmawaApprovalIndexRoute
}

const KetuaOrmawaRouteRouteChildren: KetuaOrmawaRouteRouteChildren = {
  KetuaOrmawaIndexRoute: KetuaOrmawaIndexRoute,
  KetuaOrmawaApprovalEditorRoute: KetuaOrmawaApprovalEditorRoute,
  KetuaOrmawaApprovalIndexRoute: KetuaOrmawaApprovalIndexRoute,
}

const KetuaOrmawaRouteRouteWithChildren =
  KetuaOrmawaRouteRoute._addFileChildren(KetuaOrmawaRouteRouteChildren)

interface PeminjamRouteRouteChildren {
  PeminjamReservasiRoute: typeof PeminjamReservasiRoute
  PeminjamIndexRoute: typeof PeminjamIndexRoute
  PeminjamPinjamDetailTempatRoute: typeof PeminjamPinjamDetailTempatRoute
  PeminjamPinjamEditDokumenRoute: typeof PeminjamPinjamEditDokumenRoute
  PeminjamPinjamProposalRoute: typeof PeminjamPinjamProposalRoute
  PeminjamPinjamTandaTanganRoute: typeof PeminjamPinjamTandaTanganRoute
  PeminjamPinjamIndexRoute: typeof PeminjamPinjamIndexRoute
}

const PeminjamRouteRouteChildren: PeminjamRouteRouteChildren = {
  PeminjamReservasiRoute: PeminjamReservasiRoute,
  PeminjamIndexRoute: PeminjamIndexRoute,
  PeminjamPinjamDetailTempatRoute: PeminjamPinjamDetailTempatRoute,
  PeminjamPinjamEditDokumenRoute: PeminjamPinjamEditDokumenRoute,
  PeminjamPinjamProposalRoute: PeminjamPinjamProposalRoute,
  PeminjamPinjamTandaTanganRoute: PeminjamPinjamTandaTanganRoute,
  PeminjamPinjamIndexRoute: PeminjamPinjamIndexRoute,
}

const PeminjamRouteRouteWithChildren = PeminjamRouteRoute._addFileChildren(
  PeminjamRouteRouteChildren,
)

interface SumberDayaRouteRouteChildren {
  SumberDayaIndexRoute: typeof SumberDayaIndexRoute
  SumberDayaApprovalIndexRoute: typeof SumberDayaApprovalIndexRoute
}

const SumberDayaRouteRouteChildren: SumberDayaRouteRouteChildren = {
  SumberDayaIndexRoute: SumberDayaIndexRoute,
  SumberDayaApprovalIndexRoute: SumberDayaApprovalIndexRoute,
}

const SumberDayaRouteRouteWithChildren = SumberDayaRouteRoute._addFileChildren(
  SumberDayaRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  KemahasiswaanRouteRoute: KemahasiswaanRouteRouteWithChildren,
  KetuaOrmawaRouteRoute: KetuaOrmawaRouteRouteWithChildren,
  PeminjamRouteRoute: PeminjamRouteRouteWithChildren,
  SumberDayaRouteRoute: SumberDayaRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  LoginOptionRoute: LoginOptionRoute,
  DosenPendampingIndexRoute: DosenPendampingIndexRoute,
  KetuaDepartemenIndexRoute: KetuaDepartemenIndexRoute,
  SenatIndexRoute: SenatIndexRoute,
  Wadek1IndexRoute: Wadek1IndexRoute,
  DosenPendampingApprovalEditorRoute: DosenPendampingApprovalEditorRoute,
  KetuaDepartemenApprovalEditorRoute: KetuaDepartemenApprovalEditorRoute,
  SenatApprovalEditorRoute: SenatApprovalEditorRoute,
  Wadek1ApprovalEditorRoute: Wadek1ApprovalEditorRoute,
  DosenPendampingApprovalIndexRoute: DosenPendampingApprovalIndexRoute,
  KetuaDepartemenApprovalIndexRoute: KetuaDepartemenApprovalIndexRoute,
  SenatApprovalIndexRoute: SenatApprovalIndexRoute,
  Wadek1ApprovalIndexRoute: Wadek1ApprovalIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
